<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [80]:
%%sql
WITH cohort_years AS (
SELECT DISTINCT
    customerkey,
    MIN(orderdate) AS cohort_year,
    MAX(COUNT(orderdate)) OVER(PARTITION BY customerkey) AS sales_per_customer
  FROM
    sales
  GROUP BY
    customerkey
  ORDER BY
    cohort_year
)
SELECT
  c.customerkey,
  c.sales_per_customer
FROM
 cohort_years AS c
LEFT JOIN sales AS s ON c.customerkey=s.customerkey
ORDER BY
  c.sales_per_customer
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

RuntimeError: (The named parameters feature is "disabled". Enable it with: %config SqlMagic.named_parameters="enabled".
For more info, see the docs: https://jupysql.ploomber.io/en/latest/api/configuration.html#named-parameters)
(psycopg2.errors.WindowingError) window functions are not allowed in GROUP BY
LINE 4:     EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY custo...
                              ^

[SQL: WITH cohort_years AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey))AS cohort_year,
    COUNT(orderdate) OVER(PARTITION BY customerkey) AS sales_per_customer
  FROM
    sales
  GROUP BY
    customerkey,
    cohort_year
  ORDER BY
    cohort_year
  LIMIT 10
)
SELECT
  c.customerkey,
  c.sales_per_customer
FROM
 cohort_years AS c
LEFT JOIN sales AS s ON c.customerkey=s.customerkey
GROUP BY
  c.customerkey
ORDER BY
  c.sales_per_customer
LIMIT 10]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [95]:
%%sql
WITH cohorts AS(
  SELECT
      customerkey,
      MIN(orderdate) AS cohort,
      COUNT(orderdate) AS sales_per_customer
    FROM
      sales
    GROUP BY
      customerkey
)
SELECT
  c.customerkey,
  EXTRACT(YEAR FROM c.cohort) AS cohort_year,
  c.sales_per_customer
FROM
  cohorts AS c
ORDER BY
  sales_per_customer DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  sales_per_customer
0          1834524        2018                  31
1          1375597        2019                  30
2           249557        2016                  27
3           459519        2019                  26
4          1801215        2016                  26
...            ...         ...                 ...
49482      1562346        2021                   1
49483      1806713        2023                   1
49484      2046925        2020                   1
49485      1849150        2022                   1
49486      1780112        2019                   1

[49487 rows x 3 columns]

In [112]:
%%sql
WITH cohort AS(
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) ) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year
  FROM
    sales
    )

SELECT
   c.customerkey,
   c.cohort_year,
   c.purchase_year,
   COUNT(c.customerkey) OVER(PARTITION BY c.cohort_year)
FROM
  cohort AS c
ORDER BY
  RANDOM()
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

RuntimeError: (The named parameters feature is "disabled". Enable it with: %config SqlMagic.named_parameters="enabled".
For more info, see the docs: https://jupysql.ploomber.io/en/latest/api/configuration.html#named-parameters)
(psycopg2.errors.GroupingError) column "sales.customerkey" must appear in the GROUP BY clause or be used in an aggregate function
LINE 3:     customerkey,
            ^

[SQL: WITH cohort AS(
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) ) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year
  FROM
    sales
    )

SELECT
   c.customerkey,
   c.cohort_year,
   c.purchase_year,
   COUNT(c.customerkey) OVER(PARTITION BY c.cohort_year)
FROM
  cohort AS c
ORDER BY
  RANDOM()
LIMIT 10]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [103]:
%%sql
SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) ) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year
  FROM
    sales
  GROUP BY
    customerkey,
    purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

76272 rows affected.

       customerkey cohort_year purchase_year
0               15        2021          2021
1              180        2018          2018
2              180        2023          2023
3              185        2019          2019
4              243        2016          2016
...            ...         ...           ...
76267      2099697        2022          2022
76268      2099711        2016          2016
76269      2099711        2017          2017
76270      2099743        2022          2022
76271      2099743        2023          2023

[76272 rows x 3 columns]